### ISSUE TITLE
Support for Java OpenJDK 21

### ISSUE THREAD

**Issue by smile37773** [paketo-buildpacks/microsoft-openjdk#202]
The Microsoft Java OpenJDK 21 has been [released](https://microsoft.sharepoint.com/teams/JavaatMicrosoft/SitePages/Announcing-Java-OpenJDK-21.aspx?forceLocale=zh-Hans&xsdata=MDV8MDF8fGJlMzU0N2QzMzY2YzQzODFlMWM1MDhkYmMwOGZkYjQ2fDcyZjk4OGJmODZmMTQxYWY5MWFiMmQ3Y2QwMTFkYjQ3fDB8MHw2MzgzMTU0OTYyOTQ5MjUzNDB8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPalEwTlRkaVltRmlMVE16TnpRdE5HTTBNaTA0T1RCbExUUmlZV1V4TldKa09UUXlOMTloWkRobU5USmhaUzFpTUdRNUxUUmlZalV0WW1ReU1pMDVOelF3TW1aaVlqTTNaV0pBZFc1eExtZGliQzV6Y0dGalpYTXZiV1Z6YzJGblpYTXZNVFk1TlRrMU1qZ3lPRFF5Tmc9PXxkZTMxYzZlZWFiODE0N2Y0ZTFjNTA4ZGJjMDhmZGI0NnwzNTM1NmYyN2YzODY0NTE1OGEwY2UxZTcyN2Q4ZTBkMg%3d%3d&sdata=aE1hN3k5Znh4R3ovQi8xNVNUek1aZHVzYk9mTERld05ybEZtSHp5OWZrMD0%3d&ovuser=72f988bf-86f1-41af-91ab-2d7cd011db47%2cqingyliu%40microsoft.com&OR=Teams-HL&CT=1696740786583&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA5MTQxNzUwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3d%3d&SafelinksUrl=https%3a%2f%2fmicrosoft.sharepoint.com%2fteams%2fJavaatMicrosoft%2fSitePages%2fAnnouncing-Java-OpenJDK-21.aspx)

When will it be supported in the buildpacks?

**Comment by eddumelendez** [comment]
There is a PR open already. See https://github.com/paketo-buildpacks/microsoft-openjdk/pull/201
