### ISSUE TITLE
 microsoft-openjdk buildpack can't figure out JDK version in MANIFEST.MF automatically 

### ISSUE THREAD

**Issue by zhoufenqin** [paketo-buildpacks/microsoft-openjdk#76]
## What happened?
If the customer doesn't input `BP_JVM_VERSION` directly, the buildpack will try to detect the right JDK version automatically, the  [logic](https://github.com/paketo-buildpacks/libjvm/blob/a44f048598dcf6d9f1f5296719342c2878823c4e/jvm_version.go#L15) from highest to low is
1. BP_JVM_VERSION
2. Build-Jdk-Spec (in MANIFEST.MF)
3. Build-Jdk (in MANIFEST.MF)
4. Buildpack default (Java 11)

But when I set the JAVA version(1.8) into MANIFEST.MF and didn't set "BP_JVM_VERSION" manually, the finally JDK version still uses the default one(JAVA 11), see
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifestEntries>
              <Build-Jdk-Spec>1.8</Build-Jdk-Spec>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
```
```
$ cat MANIFEST.MF
Manifest-Version: 1.0
Created-By: Maven Archiver 3.4.0
Implementation-Title: echo-app
Implementation-Version: 0.0.1-SNAPSHOT
Build-Jdk-Spec: 1.8
Main-Class: org.springframework.boot.loader.JarLauncher
Start-Class: com.azure.spring.cloud.test.config.client.Application
Spring-Boot-Version: 2.2.13.RELEASE
Spring-Boot-Classes: BOOT-INF/classes/
Spring-Boot-Lib: BOOT-INF/lib/
```

```
$ /layers/paketo-buildpacks_microsoft-openjdk/jdk/bin/java -version
openjdk version "11.0.13" 2021-10-19 LTS
OpenJDK Runtime Environment Microsoft-27990 (build 11.0.13+8-LTS)
OpenJDK 64-Bit Server VM Microsoft-27990 (build 11.0.13+8-LTS, mixed mode)
```

I think the route cause is here:
1. microsoft-openjdk buildpack set default java version to BP_JVM_VERSION in [buildpack.toml](https://github.com/paketo-buildpacks/microsoft-openjdk/blob/main/buildpack.toml#L112)
2. During the build process, it will figure out the JDK version, before stepping into [GetJVMVersion](https://github.com/paketo-buildpacks/libjvm/blob/eb10f2bbb3d85575b1a2135d10c9257c6cb7d637/build.go#L59) logic, it will resolve buildpack configurations, then the `BP_JVM_VERSION` under `[[metadata.configurations]]` in `buildpack.toml` will be loaded, BP_JVM_VERSION is higher than `Build-Jdk-Spec`, then the user-set JDK version won't be set.
  - [step1](https://github.com/paketo-buildpacks/libjvm/blob/eb10f2bbb3d85575b1a2135d10c9257c6cb7d637/build.go#L37)
  - [step2](https://github.com/paketo-buildpacks/libpak/blob/main/buildpack.go#L300)
  - [step3](https://github.com/paketo-buildpacks/libpak/blob/main/buildpack.go#L359)
```
// build log
Paketo Microsoft OpenJDK Buildpack 2.0.1
  https://github.com/paketo-buildpacks/microsoft-openjdk
  Build Configuration:
    $BP_JVM_TYPE                 JRE             the JVM type - JDK or JRE
    $BP_JVM_VERSION              11              the Java version
  Launch Configuration:
  ......
```

Is it correct?

* What were you attempting to do?
Config JDK version in pom.xml with manifest config, hope the buildpack can detect the JAVA version by `Build-Jdk-Spec` in MENIFEST.MF
```
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-jar-plugin</artifactId>
        <configuration>
          <archive>
            <manifestEntries>
              <Build-Jdk-Spec>1.8</Build-Jdk-Spec>
            </manifestEntries>
          </archive>
        </configuration>
      </plugin>
```

* What did you expect to happen?
It will pick up the JDK 8 configured in pom.xml

* What was the actual behavior? Please provide log output, if possible.
The `Build-Jdk-Spec` didn't work, it still using the default JAVA 11

## Build Configuration

* What platform (`pack`, `kpack`, `tekton` buildpacks plugin, etc.) are you
  using? Please include a version.

kpack

* What buildpacks are you using? Please include versions.
https://github.com/pivotal-cf/tanzu-java-azure
this includes this `microsoft-openjdk` buildpack

* What builder are you using? If custom, can you provide the output from `pack
  inspect-builder <builder>`?

* Can you provide a sample app or relevant configuration (`buildpack.yml`,
  `nginx.conf`, etc.)?

## Checklist

* [ ] I have included log output.
* [ ] The log output includes an error message.
* [ ] I have included steps for reproduction.

**Comment by dmikusa-pivotal** [comment]
Apologizes. I don't think we'd released this functionality with the Microsoft OpenJDK CNB. Try with Paketo Microsoft OpenJDK Buildpack 2.2.1 (I just cut this release). That should work for you.

We'll pull Paketo Microsoft OpenJDK Buildpack 2.2.1 into the Paketo & Tanzu Java Azure buildpacks on Friday.

**Comment by dmikusa-pivotal** [comment]
I believe we resolved this via discussion through another channel. It needed the buildpack version bump as mentioned above and it also only works when pushing pre-compiled assets. This makes sense given that the metadata comes from the JAR/WAR file and we need to determine the Java version prior to installing any tools, which would be prior to building any code into a JAR/WAR.

Closing this. If there's more questions, please feel free to reach out.
